name: build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: blogit-bot
        uses: renzholy/blogit@v0.0.7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          owner: renzholy
          repo: blog
          branch: main
          index: README
          links: Home,README;About,ABOUT;GitHub,https://github.com/renzholy;Twitter,http://twitter.com/rezholy;Jike,https://web.okjike.com/u/d25026f2-18ce-48aa-9ea7-c05a25446368
