name: build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: blogit-bot
        uses: RenzHoly/blogit@v0.0.2
        env:
          GHP: ${{ secrets.GITHUB_TOKEN }}
          NEXT_PUBLIC_OWNER: RenzHoly
          NEXT_PUBLIC_REPO: blog
          NEXT_PUBLIC_BRANCH: main
          NEXT_PUBLIC_INDEX: README
          NEXT_PUBLIC_LINKS: Home,README;About,ABOUT;GitHub,https://github.com/RenzHoly;Twitter,http://twitter.com/rezholy;Jike,https://web.okjike.com/u/d25026f2-18ce-48aa-9ea7-c05a25446368
