name: build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # - uses: actions/checkout@v2

      - name: blogit-bot
        uses: renzholy/blogit@v0.0.17
        env:
          GHP: ${{ secrets.GITHUB_TOKEN }}
          NEXT_PUBLIC_OWNER: renzholy
          NEXT_PUBLIC_REPO: renzholy.github.io
          NEXT_PUBLIC_BRANCH: main
          NEXT_PUBLIC_INDEX: readme
          NEXT_PUBLIC_LINKS: Home,/readme;About,/about;GitHub,https://github.com/renzholy;Twitter,http://twitter.com/renzholy;Jike,https://web.okjike.com/u/d25026f2-18ce-48aa-9ea7-c05a25446368

      - name: Deploy to GitHub Pages
        if: success()
        uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: gh-pages
          build_dir: out
          fqdn: fpt.ink
          jekyll: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
